FROM node:lts-slim

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/server ./apps/server

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run db:generate
RUN pnpm run build

EXPOSE 8080

CMD [ "pnpm", "run", "start:server" ]




