FROM node:lts-slim

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/client ./apps/client

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run build

EXPOSE 5173

CMD [ "pnpm", "run", "start:client" ]