FROM node:22.19.0-alpine3.22

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/server ./apps/server

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm db:generate
RUN pnpm run build:server

EXPOSE 8080

CMD [ "sh", "-c", "pnpm db:generate && pnpm start:server" ]