name: Deploy to staging

on:
  push:
    branches: [ "dev" ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging server
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.STAGING_IP }} -t "
            cd tally-v1 &&
            git pull origin dev &&
            export PATH=/root/.nvm/versions/node/v22.13.1/bin:\$PATH &&
            pnpm install -g pnpm &&
            pnpm install &&
            pnpm run build &&
            pm2 restart staging-tally-api
          "
