name: Stagging DEployment

on:
  push:
    branches: ["dev"]

jobs:
  Re-Deployment of client & server:
    runs-on: ubuntu-latest
    name: Re-Deployment of client & server to stagging server
    steps:
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ssh_key
        echo "${{ secrets.STAGGING_IP }}" &> ip
        echo "yes" | ssh -i ssh_key ubuntu@ip -t "
        cd tally-v1 && 
        git pull origin dev &&
        export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin &&
        pnpm install -g pnpm &&
        pnpm install &&
        pnpm run build &&
        pm2 restart stagging-tally-api
        "

