name: Deploy Frontend to S3 + CloudFront

on:
  push:
    branches:
      - main
    # paths:
    #   - "apps/client/**"
    #   - "packages/**"

jobs:
  deploy-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build React app
        run: |
          cd ./apps/client
          pnpm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ENV_PROD: ${{ secrets.VITE_ENV_PROD }}
          VITE_DEV_DOMAIN: ${{ secrets.VITE_DEV_DOMAIN }}
          VITE_PROD_DOMAIN: ${{ secrets.VITE_PROD_DOMAIN }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_LOGIN_URL: ${{ secrets.VITE_GOOGLE_LOGIN_URL }}
          VITE_GOOGLE_SHEET_LOGIN_URL: ${{ secrets.VITE_GOOGLE_SHEET_LOGIN_URL }}
          VITE_NOTION_LOGIN_URL: ${{ secrets.VITE_NOTION_LOGIN_URL }}

      - name: Sync build folder to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.FORMIQ_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REGION }}
          SOURCE_DIR: ./apps/client/dist

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.DISTRIBUTION_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
